version: '3'
services:
  app:
    build: .
    image: hexo_app
    container_name: nuinfo-seminar-app
    volumes: 
      - .:/app
    ports:
      - 4000:4000
    tty: true
    environment:
      TZ: Asia/Tokyo